apiVersion: v1
data:
  # https://bcrypt-generator.com/
  # dci-admin:3cnjoBgrMoKkv78s
  # dci-admin:$2a$12$aXWmY9nInWvBehl/eoRfTO2Yh3vMAbCpQbwQEZaZcoIu.TRmMzone
  auth: Z3hjLWFkbWluOiQyYSQxMiRhWFdtWTluSW5XdkJlaGwvZW9SZlRPMlloM3ZNQWJDcFFid1FFWmFaY29JdS5UUm1Nem9uZQo=
  username: "Z3hjLWFkbWluCg=="
  password: "M2Nuam9CZ3JNb0trdjc4cwo="
kind: Secret
metadata:
  name: dci-auth
  namespace: devops-tools
type: Opaque
