apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dci-staging
  labels:
    name: dci-staging
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: support@devopscorner.id
    privateKeySecretRef:
      name: dci-staging
    solvers:
      - http01:
          ingress:
            class: nginx
      - dns01:
          route53:
            hostedZoneID: Z04003073DCF9BY5JJQFT
            region: ap-southeast-3
            secretAccessKeySecretRef:
              name: ""